name = Fita Simple
description = A simple 3 column layout for Fita theme.
preview = preview.png
template = fita-simple-layout

; Regions
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/fita-simple/fita-simple.layout.css
